apiVersion: v1
kind: Service
metadata:
  name: test555555
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: test555555